export const ImageConstant = {
  BackGroundImage: require('../../assets/Images/background.png'),
  FaceBook: require('../../assets/Images/FaceBook.png'),
  Apple: require('../../assets/Images/Apple.png'),
  Google: require('../../assets/Images/Google.png'),
  BackArrow: require('../../assets/Images/backArrow.png'),
  profile: require('../../assets/Images/profile.png'),
  email: require('../../assets/Images/Email.png'),
  lang: require('../../assets/Images/lang.png'),
  active: require('../../assets/Images/active.png'),
  inActive: require('../../assets/Images/inActive.png'),
  home: require('../../assets/Images/home.png'),
  Preferences: require('../../assets/Images/Preferences.png'),
  Temple: require('../../assets/Images/Temple.png'),
  Festivals: require('../../assets/Images/Festivals.png'),
  setting: require('../../assets/Images/setting.png'),
  Camra: require('../../assets/Images/Camra.png'),
  TestProfile: require('../../assets/Images/TestProfile.png'),
  Draw: require('../../assets/Images/Draw.png'),
  Notification: require('../../assets/Images/Notification.png'),
  location: require('../../assets/Images/location.png'),
  HomeBack: require('../../assets/Images/HomeBack.png'),
  reminder: require('../../assets/Images/reminder.png'),
  calander: require('../../assets/Images/calander.png'),
  about: require('../../assets/Images/about.png'),
  help: require('../../assets/Images/help.png'),
  delete: require('../../assets/Images/delete.png'),
  faq: require('../../assets/Images/faq.png'),
  logout: require('../../assets/Images/logout.png'),
  radioActive: require('../../assets/Images/radioActive.png'),
  radioInactive: require('../../assets/Images/radioInactive.png'),
  Card: require('../../assets/Images/Card.png'),
  LeftTri: require('../../assets/Images/LeftTri.png'),
  rigthTri: require('../../assets/Images/rightTri.png'),
  Tip1: require('../../assets/Images/Tip1.png'),
  Tip2: require('../../assets/Images/Tip2.png'),
  Festival1: require('../../assets/Images/Festival1.png'),
  Festival2: require('../../assets/Images/Festival2.png'),
  Festival3: require('../../assets/Images/Festival3.png'),
  girl: require('../../assets/Images/girl.png'),
  baba: require('../../assets/Images/baba.png'),
  rightarrow: require('../../assets/Images/rightarrow.png'),
  shiv: require('../../assets/Images/Shiv.png'),
  search: require('../../assets/Images/search.png'),
  share: require('../../assets/Images/Share.png'),
  DeleteIcon: require('../../assets/Images/DeleteIcon.png'),
  EditIcon: require('../../assets/Images/EditIcon.png'),
  watch: require('../../assets/Images/watch.png'),
  notificationgray: require('../../assets/Images/notificationgray.png'),
  off: require('../../assets/Images/off.png'),
  whatsapp: require('../../assets/Images/whatsapp.png'),
  emails: require('../../assets/Images/emails.png'),
  cal: require('../../assets/Images/cal.png'),
  checked: require('../../assets/Images/checked.png'),
  unchecked: require('../../assets/Images/unchecked.png'),
  Festival:require("../../assets/Images/Festival.png"),
  Amavasya:require("../../assets/Images/Amavasya.png"),
  ekadashi:require("../../assets/Images/11.png"),
  sankranti:require("../../assets/Images/sankranti.png"),
  Pournami:require("../../assets/Images/Pournami.png"),
  FestivalNew:require("../../assets/Images/FestivalNew.png"),
  botmreme:require("../../assets/Images/botmreme.png"),
  bell:require("../../assets/Images/bell.png"),
};
