import LocalizedStrings from 'react-native-localization';
import Privacy from './../Screens/Private/Setting/Privacy';
import Terms from './../Screens/Private/Setting/Terms';

export default new LocalizedStrings({
  // English
  en: {
    Home: {
      Home: 'Home',
      Good_morn: 'Good Morning!',
      sunrise: 'Sunrise',
      sunset: 'Sunset',
      today_pan: 'Today Panchang',
      calandar: 'Calendar',
      upcoming: 'Upcoming Festivals',
      tips: 'Tip of the Day',
      night: 'Good Night!',
      morning: 'Good Morning!',
      afternoon: 'Good Afternoon!',
      evening: 'Good Evening!',
      all_festivals: 'All Festivals',
    },
    Preferences: {
      my_profile: 'My Profile',
      email: 'Email Address',
      phone: 'Whatsapp Number',
      select_country: 'Select Country',
      select_state: 'Select State',
      language: 'Select Language',
      notify: 'Notify',
      update: 'Update Profile',
      Preferences: 'Preferences',
      Name: 'Name',
    },
    Settings: {
      title: 'Settings',
      alluse: 'All Your Important Dates, Notifications & Reminders',
      notif: 'Stay Updated with All the Latest Activity, Instantly',
      reminders: 'Reminders',
      remindersSubtitle: 'Muhurat and Event Reminders',
      helpu: 'Get the Help You Need, When You Need It',
      notifications: 'Notifications',
      notificationsSubtitle: 'Customize Push Notification',
      whatsapp: 'Message us on WhatsApp',
      about: 'About App',
      aboutSubtitle: 'Remyndnow App Details',
      help: 'Help & Support',
      helpSubtitle: 'Need Support? Reach Out Easily',
      delete: 'Delete Your Account',
      deleteSubtitle: "We're sorry to see you go.",
      faq: "FAQ's",
      faqSubtitle: 'All You Need to Know',
      logout: 'LOG OUT',
      Privacy: 'Privacy policy',
      Terms_cond: 'terms and conditions',
      accountDeleteTitle: 'Account Delete',
      accountDeleteSubtitle: "We're sorry to see you go.",
      accountDeleteDesc:
        'Deleting your account is permanent. All your data, bookings, messages, and photos will be erased. This action cannot be reversed.',

      reasonPlaceholder: "I don't find this app useful",
      reasonPrivacy: 'I have privacy concerns',
      reasonTooManyNotifications: "I'm getting too many notifications",
      reasonDuplicate: 'I created a duplicate account',
      reasonOther: 'Other',
      reasonOtherPlaceholder: 'enter',

      deleteButton: 'DELETE ACCOUNT',
      cancelButton: 'CANCEL',

      confirmTitle: 'Are you sure?',
      confirmDesc: 'This action is permanent. All your data will be deleted.',
      confirmCancel: 'NO, KEEP MY ACCOUNT',
      confirmDelete: 'YES, DELETE',
      suport_title: 'Have questions or feedback?',
      suport_subtitle:
        'If you have any questions, feedback, or even suggestions to help us improve, please dont hesitate to reach out. We truly value your thoughts and would love to hear how we can make Remyndnow better for you. Just send us an email — were always listening.',
    },
    DeleteAccount: {
      title: 'Account Delete',
      subtitle: "We're sorry to see you go.",
      reason_label: 'Reason for Leaving',
      placeholder: 'enter',
      delete_btn: 'DELETE ACCOUNT',
      cancel_btn: 'CANCEL',
      confirm_title: 'Are you sure?',
      confirm_desc: 'This action is permanent. All your data will be deleted.',
      keep_account: 'NO, KEEP MY ACCOUNT',
      yes_delete: 'YES, DELETE',
    },
    Festivals: {
      title: 'Festivals',
      month: 'July 2023',
      know_more: 'Know More',
      no_festivals: 'No festivals found for this month.',
      upcoming_festivals: 'Upcoming Festivals',
      view_details: 'VIEW DETAILS',
      search: 'Search',
    },
    Temple: {
      Temple: 'Temple',
      aboutTitle: 'About OurTemples.info',
      aboutText1: 'Explore Hindu Temples with Rich, Trusted Details. Visit',
      aboutText2:
        ', a one-stop portal offering Hindu temples across India, thoughtfully categorized by region and deity.',
      ourTemples: 'Our Temples',
      points:
        '• History & Significance – The heritage and stories behind each sacred place\n\n• Timings & Pooja Details – Opening hours, daily rituals, and special pooja schedules\n\n• How to Reach & Nearby Features – Directions, local geography, and nearby temples or points of interest',
      closingText:
        "Whether you're planning a pilgrimage or simply exploring spiritual heritage from home,",
      closingText2:
        'is your trusted guide—curated by volunteers and aimed at devotees like you.',
    },
    HomeDetails: {
      reminderMe: 'REMINDER ME',
      reminderEnabled: 'REMINDER ENABLED',
      panchangTitle: 'Panchag',
      panchangFor: 'PANCHAG FOR',
      aboutFestival: 'About Festival',
      festivalHighlights: 'Festival Highlights',
      regionalNames: 'Regional Names',
      duration: 'Duration',
      dailySignificance: 'Daily Significance',
      history: 'History',
      templesToVisit: 'Temples to Visit',
      otherInfo: 'Other Information',
      statesCelebrated: 'States Celebrated',
      upcomingFestivals: 'Upcoming Festivals',
      upcomingDates: 'Upcoming Dates',
      Vrat: 'Select Festival/Vrat',
      setReminder: 'Set a Reminder',
      reminderDesc: ` We'll remind you at 6 a.m. these days`,
      startPhrase: 'We will remind you at',
      endPhrase: 'on these days',
      beforeEkadashi: 'Before',
      onEkadashi: 'On each',
      cancel: 'CANCEL',
      confirm: 'CONFIRM',
      select_language: 'Select Language',
      description: 'We have following language available',
      continue: 'Continue',
    },
  },

  // Hindi
  hi: {
    Home: {
      Home: 'होम',
      Good_morn: 'सुप्रभात!',
      sunrise: 'सूर्योदय',
      sunset: 'सूर्यास्त',
      today_pan: 'आज का पंचांग',
      calandar: 'कैलेंडर',
      upcoming: 'आगामी त्योहार',
      tips: 'आज की सलाह',
      night: 'शुभ रात्रि!',
      morning: 'सुप्रभात!',
      afternoon: 'नमस्ते दोपहर!',
      evening: 'शुभ संध्या!',
      all_festivals: 'सभी त्यौहार',
    },
    Preferences: {
      my_profile: 'मेरी प्रोफ़ाइल',
      email: 'ईमेल पता',
      phone: 'व्हाट्सएप नंबर',
      select_country: 'देश चुनें',
      select_state: 'राज्य चुनें',
      language: 'भाषा',
      notify: 'सूचित करें',
      update: 'प्रोफ़ाइल अपडेट करें',
      Preferences: 'प्राथमिकताएँ',
      Name: 'नाम',
    },
    Settings: {
      title: 'सेटिंग्स',
      alluse: 'आपकी सभी महत्वपूर्ण तिथियाँ, सूचनाएँ और अनुस्मारक',
      notif: 'सभी नवीनतम गतिविधियों से तुरंत अपडेट रहें',
      reminders: 'अनुस्मारक',
      remindersSubtitle: 'मुहूर्त और इवेंट अनुस्मारक',
      helpu: 'जब भी आवश्यकता हो, मदद प्राप्त करें',
      notifications: 'सूचनाएं',
      notificationsSubtitle: 'पुश सूचनाओं को अनुकूलित करें',
      whatsapp: 'हमें व्हाट्सएप पर संदेश भेजें',
      about: 'ऐप के बारे में',
      aboutSubtitle: 'Remyndnow ऐप विवरण',
      help: 'सहायता और समर्थन',
      helpSubtitle: 'सहायता चाहिए? आसानी से संपर्क करें',
      delete: 'अपना खाता हटाएं',
      deleteSubtitle: 'हमें खेद है कि आप जा रहे हैं।',
      faq: 'अक्सर पूछे जाने वाले प्रश्न',
      faqSubtitle: 'आपको जानने के लिए सब कुछ',
      logout: 'लॉग आउट',
      Privacy: 'गोपनीयता नीति',
      Terms_cond: 'नियम और शर्तें',
      accountDeleteTitle: 'खाता हटाएं',
      accountDeleteSubtitle: 'हमें खेद है कि आप जा रहे हैं।',
      accountDeleteDesc:
        'खाता हटाना स्थायी है। आपका सारा डेटा, बुकिंग, संदेश और फ़ोटो हटा दिए जाएंगे। यह क्रिया पूर्ववत नहीं की जा सकती।',

      reasonPlaceholder: 'मुझे यह ऐप उपयोगी नहीं लगता',
      reasonPrivacy: 'मेरी गोपनीयता को लेकर चिंता है',
      reasonTooManyNotifications: 'मुझे बहुत अधिक सूचनाएं मिल रही हैं',
      reasonDuplicate: 'मैंने डुप्लिकेट खाता बनाया है',
      reasonOther: 'अन्य',
      reasonOtherPlaceholder: 'लिखें',

      deleteButton: 'खाता हटाएं',
      cancelButton: 'रद्द करें',

      confirmTitle: 'क्या आप सुनिश्चित हैं?',
      confirmDesc: 'यह कार्रवाई स्थायी है। आपका सारा डेटा हटा दिया जाएगा।',
      confirmCancel: 'नहीं, मेरा खाता रखें',
      confirmDelete: 'हाँ, हटाएं',
      suport_title: 'कोई प्रश्न या सुझाव?',
      suport_subtitle:
        'यदि आपके पास कोई प्रश्न, प्रतिक्रिया, या सुधार के लिए सुझाव हैं, तो कृपया हमें बताने में संकोच न करें। हम आपकी राय को महत्व देते हैं और जानना चाहेंगे कि Remyndnow को आपके लिए बेहतर कैसे बनाया जाए। हमें सिर्फ एक ईमेल भेजें — हम हमेशा सुनने के लिए तैयार हैं।',
    },
    DeleteAccount: {
      title: 'खाता हटाएं',
      subtitle: 'हमें खेद है कि आप जा रहे हैं।',
      reason_label: 'छोड़ने का कारण',
      placeholder: 'यहाँ लिखें',
      delete_btn: 'खाता हटाएं',
      cancel_btn: 'रद्द करें',
      confirm_title: 'क्या आप सुनिश्चित हैं?',
      confirm_desc: 'यह कार्रवाई स्थायी है। आपका सारा डेटा हटा दिया जाएगा।',
      keep_account: 'नहीं, मेरा खाता रखें',
      yes_delete: 'हाँ, हटाएं',
    },
    Festivals: {
      title: 'त्योहार',
      month: 'जुलाई 2023',
      know_more: 'और जानें',
      no_festivals: 'इस महीने के लिए कोई त्योहार नहीं मिला।',
      upcoming_festivals: 'आगामी त्योहार',
      view_details: 'विवरण देखें',
      search: 'खोजें',
    },
    Temple: {
      Temple: 'मंदिर',
      aboutTitle: 'हमारे OurTemples.info के बारे में',
      aboutText1:
        'समृद्ध और विश्वसनीय विवरणों के साथ हिंदू मंदिरों का अन्वेषण करें। जाएं',
      aboutText2:
        ', एक ऐसा पोर्टल जो पूरे भारत के हिंदू मंदिरों को क्षेत्र और देवता के अनुसार श्रेणीबद्ध करता है।',
      ourTemples: 'हमारे मंदिर',
      points:
        '• इतिहास और महत्व – प्रत्येक पवित्र स्थान की विरासत और कहानियाँ\n\n• समय और पूजा विवरण – खुलने का समय, दैनिक अनुष्ठान और विशेष पूजा कार्यक्रम\n\n• कैसे पहुँचे और आस-पास की जानकारी – दिशा-निर्देश, स्थानीय भूगोल और निकटवर्ती मंदिर या अन्य आकर्षण',
      closingText:
        'चाहे आप तीर्थ यात्रा की योजना बना रहे हों या घर से आध्यात्मिक धरोहर का अन्वेषण कर रहे हों,',
      closingText2:
        'आपका विश्वसनीय मार्गदर्शक है—स्वयंसेवकों द्वारा संकलित और आपके जैसे भक्तों के लिए।',
    },
    HomeDetails: {
      reminderMe: 'मुझे याद दिलाएं',
      reminderEnabled: 'रिमाइंडर सक्षम है',
      panchangTitle: 'पंचांग',
      panchangFor: 'के लिए पंचांग',
      aboutFestival: 'त्योहार के बारे में',
      festivalHighlights: 'त्योहार की मुख्य बातें',
      regionalNames: 'क्षेत्रीय नाम',
      duration: 'अवधि',
      dailySignificance: 'दैनिक महत्व',
      history: 'इतिहास',
      templesToVisit: 'दर्शन योग्य मंदिर',
      otherInfo: 'अन्य जानकारी',
      statesCelebrated: 'मानने वाले राज्य',
      upcomingFestivals: 'आगामी त्योहार',
      setReminder: 'रिमाइंडर सेट करें',
      reminderDesc: 'हम आपको इन दिनों सुबह 6 बजे याद दिलाएंगे',
      startPhrase: 'हम आपको इन दिनों',
      endPhrase: 'बजे याद दिलाएंगे',
      beforeEkadashi: 'पहले',
      onEkadashi: 'प्रत्येक',
      cancel: 'रद्द करें',
      confirm: 'पुष्टि करें',
      Vrat: 'त्यौहार/व्रत चुनें',
      select_language: 'भाषा चुनें',
      description: 'हमारे पास निम्नलिखित भाषाएँ उपलब्ध हैं',
      continue: 'जारी रखें',
    },
  },

  // Tamil
  ta: {
    Home: {
      Home: 'முகப்பு',
      Good_morn: 'காலை வணக்கம்!',
      sunrise: 'சூரியோதயம்',
      sunset: 'சூரிய அஸ்தமனம்',
      today_pan: 'இன்றைய பஞ்சாங்கம்',
      calandar: 'நாட்காட்டி',
      upcoming: 'எதிர்வரும் விழாக்கள்',
      tips: 'இன்றைய குறிப்பு',
      night: 'இரவு வணக்கம்!',
      morning: 'காலை வணக்கம்!',
      afternoon: 'மதியம் வணக்கம்!',
      evening: 'மாலை வணக்கம்!',
      all_festivals: 'அனைத்து திருவிழாக்கள்',
    },
    Preferences: {
      my_profile: 'என் சுயவிவரம்',
      email: 'மின்னஞ்சல் முகவரி',
      phone: 'வாட்ஸ்அப் எண்',
      select_country: 'நாடு தேர்வு செய்க',
      select_state: 'மாநிலத்தை தேர்வு செய்க',
      language: 'மொழி',
      notify: 'அறிவிக்கவும்',
      update: 'சுயவிவரத்தை புதுப்பிக்கவும்',
      Preferences: 'விருப்பங்கள்',
      Name: 'பெயர்',
    },
    Settings: {
      title: 'அமைப்புகள்',
      alluse: 'உங்கள் முக்கிய தேதிகள், அறிவிப்புகள் மற்றும் நினைவூட்டல்கள்',
      notif: 'அனைத்து சமீபத்திய செயல்பாடுகளிலும் புதுப்பிக்கப்பட்டிருங்கள்',
      reminders: 'நினைவூட்டல்கள்',
      remindersSubtitle: 'முஹூர்த்தம் மற்றும் நிகழ்வு நினைவூட்டல்கள்',
      helpu: 'உங்களுக்கு தேவையான நேரத்தில் உதவியைப் பெறுங்கள்',
      notifications: 'அறிவிப்புகள்',
      notificationsSubtitle: 'புஷ் அறிவிப்புகளை தனிப்பயனாக்கவும்',
      whatsapp: 'வாட்ஸ்அப்பில் எங்களை தொடர்பு கொள்ளவும்',
      about: 'அப் பற்றியது',
      aboutSubtitle: 'Remyndnow அப் விவரங்கள்',
      help: 'உதவி மற்றும் ஆதரவு',
      helpSubtitle: 'உதவி தேவை? எளிதில் அணுகவும்',
      delete: 'உங்கள் கணக்கை நீக்கவும்',
      deleteSubtitle: 'நீங்கள் செல்லும் போது வருத்தமாக இருக்கிறது.',
      faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      faqSubtitle: 'நீங்கள் அறிய வேண்டிய அனைத்தும்',
      logout: 'வெளியேறு',
      Privacy: 'தனியுரிமைக் கொள்கை',
      Terms_cond: 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      accountDeleteTitle: 'கணக்கை நீக்கவும்',
      accountDeleteSubtitle: 'நீங்கள் செல்லும் போது வருத்தமாக இருக்கிறது.',
      accountDeleteDesc:
        'கணக்கை நீக்குவது நிரந்தரமானது. உங்கள் அனைத்து தரவுகள், முன்பதிவுகள், செய்திகள் மற்றும் படங்கள் நீக்கப்படும். இந்த செயல் மாற்ற முடியாது.',

      reasonPlaceholder: 'இந்த பயன்பாடு பயனுள்ளதாக இல்லை என்று நினைக்கிறேன்',
      reasonPrivacy: 'எனக்கு தனியுரிமை குறித்த கவலைகள் உள்ளன',
      reasonTooManyNotifications: 'எனக்கு அதிக அறிவிப்புகள் வருகின்றன',
      reasonDuplicate: 'நான் நகல் கணக்கை உருவாக்கியுள்ளேன்',
      reasonOther: 'மற்றவை',
      reasonOtherPlaceholder: 'உள்ளிடவும்',

      deleteButton: 'கணக்கை நீக்கவும்',
      cancelButton: 'ரத்து செய்க',

      confirmTitle: 'நீங்கள் உறுதியாக இருக்கிறீர்களா?',
      confirmDesc:
        'இந்த செயல் நிரந்தரமானது. உங்கள் அனைத்து தரவுகளும் நீக்கப்படும்.',
      confirmCancel: 'இல்லை, எனது கணக்கை வைத்திருக்கவும்',
      confirmDelete: 'ஆம், நீக்கவும்',
      suport_title: 'கேள்விகள் அல்லது கருத்துக்கள் உள்ளதா?',
      suport_subtitle:
        'உங்களுக்கு ஏதேனும் கேள்விகள், கருத்து அல்லது எங்களை மேம்படுத்த உதவும் பரிந்துரைகள் இருந்தால் தயங்காமல் எங்களைத் தொடர்பு கொள்ளவும். உங்கள் எண்ணங்களை நாங்கள் மதிக்கிறோம், Remyndnow-ஐ உங்கள் வாழ்வுக்கு சிறப்பாக்க எப்படிக்‌கு முடியும் என்பதைப் பகிர்ந்து கொள்ள விரும்புகிறோம். உங்கள் மின்னஞ்சலை மட்டும் அனுப்புங்கள் — நாங்கள் எப்போதும் கேட்கிறோம்.',
    },
    DeleteAccount: {
      title: 'கணக்கை நீக்கவும்',
      subtitle: 'நீங்கள் செல்லும் போது வருத்தமாக இருக்கிறது.',
      reason_label: 'விலகும் காரணம்',
      placeholder: 'உள்ளிடவும்',
      delete_btn: 'கணக்கை நீக்கவும்',
      cancel_btn: 'ரத்து செய்க',
      confirm_title: 'நீங்கள் உறுதியாக இருக்கிறீர்களா?',
      confirm_desc:
        'இந்த செயல் நிரந்தரமானது. உங்கள் அனைத்து தரவுகளும் நீக்கப்படும்.',
      keep_account: 'இல்லை, எனது கணக்கை வைத்திருக்கவும்',
      yes_delete: 'ஆம், நீக்கவும்',
    },
    Festivals: {
      title: 'விழாக்கள்',
      month: 'ஜூலை 2023',
      know_more: 'மேலும் அறிக',
      no_festivals: 'இந்த மாதத்திற்கு விழாக்கள் இல்லை.',
      upcoming_festivals: 'எதிர்வரும் விழாக்கள்',
      view_details: 'விவரங்களை பார்க்க',
      search: 'தேடல்',
    },
    Temple: {
      Temple: 'கோவில்',
      aboutTitle: 'எங்கள் OurTemples.info பற்றி',
      aboutText1:
        'பெருமைமிகு, நம்பகமான விவரங்களுடன் இந்து கோவில்களை ஆராயுங்கள். செல்லவும்',
      aboutText2:
        ', இந்தியா முழுவதும் உள்ள இந்து கோவில்களை பிராந்தியம் மற்றும் தெய்வம் அடிப்படையில் வகைப்படுத்திய ஒரே தளம்.',
      ourTemples: 'எங்கள் கோவில்கள்',
      points:
        '• வரலாறு & முக்கியத்துவம் – ஒவ்வொரு புனித தலத்தின் மரபும் கதைகளும்\n\n• நேரங்கள் & பூஜை விவரங்கள் – திறந்த நேரங்கள், அன்றாட பூஜைகள் மற்றும் சிறப்பு பூஜை அட்டவணைகள்\n\n• எப்படி செல்லலாம் & அருகிலுள்ள அம்சங்கள் – வழிகாட்டல்கள், உள்ளூர் நிலவியல் மற்றும் அருகிலுள்ள கோவில்கள் அல்லது சுற்றுலா இடங்கள்',
      closingText:
        'நீங்கள் யாத்திரை திட்டமிடுகிறீர்களா அல்லது வீட்டிலிருந்தே ஆன்மீக பாரம்பரியத்தை ஆராயுகிறீர்களா,',
      closingText2:
        'உங்கள் நம்பகமான வழிகாட்டி—தன்னார்வலர்களால் தொகுக்கப்பட்டு உங்களைப் போன்ற பக்தர்களுக்காக.',
    },
    HomeDetails: {
      reminderMe: 'எனக்கு நினைவூட்டவும்',
      reminderEnabled: 'நினைவூட்டல் இயக்கப்பட்டது',
      panchangTitle: 'பஞ்சாங்கம்',
      panchangFor: 'இற்கான பஞ்சாங்கம்',
      aboutFestival: 'திருவிழா பற்றி',
      festivalHighlights: 'திருவிழா சிறப்பம்சங்கள்',
      regionalNames: 'பிராந்திய பெயர்கள்',
      duration: 'காலம்',
      dailySignificance: 'தினசரி முக்கியத்துவம்',
      history: 'வரலாறு',
      templesToVisit: 'செல்ல வேண்டிய கோவில்கள்',
      otherInfo: 'மற்ற தகவல்கள்',
      statesCelebrated: 'கொண்டாடப்படும் மாநிலங்கள்',
      upcomingFestivals: 'வரவிருக்கும் திருவிழாக்கள்',
      setReminder: 'நினைவூட்டலை அமைக்கவும்',
      reminderDesc: 'இந்த நாட்களில் காலை 6 மணிக்கு நாங்கள் நினைவூட்டுவோம்',
      // startPhrase: 'நாங்கள் உங்களை',
      endPhrase: 'இந்த நாட்களில்',
      beforeEkadashi: 'முன்பு',
      onEkadashi: 'ஒவ்வொன்றிலும்',
      cancel: 'ரத்து செய்யவும்',
      confirm: 'உறுதிப்படுத்தவும்',
      Vrat: 'பண்டிகை/விரதத்தை தேர்ந்தெடுக்கவும்',
      select_language: 'மொழியை தேர்ந்தெடுக்கவும்',
      description: 'எங்களிடம் பின்வரும் மொழிகள் கிடைக்கின்றன',
      continue: 'தொடரவும்',
    },
  },

  // Telugu
  te: {
    Home: {
      Home: 'హోమ్',
      Good_morn: 'శుభోదయం!',
      sunrise: 'సూర్యోదయం',
      sunset: 'సూర్యాస్తమయం',
      today_pan: 'ఈరోజు పంచాంగం',
      calandar: 'క్యాలెండర్',
      upcoming: 'రాబోయే పండుగలు',
      tips: 'ఈరోజు చిట్కా',
      night: 'శుభ రాత్రి!',
      morning: 'శుభోదయం!',
      afternoon: 'మధ్యాహ్నం శుభాకాంక్షలు!',
      evening: 'సాయంత్రం శుభాకాంక్షలు!',
      all_festivals: 'అన్ని పండుగలు',
    },
    Preferences: {
      my_profile: 'నా ప్రొఫైల్',
      email: 'ఇమెయిల్ చిరునామా',
      phone: 'వాట్సాప్ నంబర్',
      select_country: 'దేశాన్ని ఎంచుకోండి',
      select_state: 'రాష్ట్రాన్ని ఎంచుకోండి',
      language: 'భాష',
      notify: 'తెలియజేయండి',
      update: 'ప్రొఫైల్ నవీకరించు',
      Preferences: 'ప్రాధాన్యతలు',
      Name: 'పేరు',
    },
    Settings: {
      title: 'సెట్టింగ్స్',
      alluse: 'మీ ముఖ్యమైన తేదీలు, నోటిఫికేషన్లు మరియు రిమైండర్లు',
      notif: 'తాజా కార్యకలాపాలన్నింటికి వెంటనే అప్‌డేట్ అవ్వండి',
      reminders: 'రిమైండర్లు',
      remindersSubtitle: 'ముహూర్తం మరియు ఈవెంట్ రిమైండర్లు',
      helpu: 'మీకు అవసరం ఉన్నప్పుడు సహాయం పొందండి',
      notifications: 'నోటిఫికేషన్లు',
      notificationsSubtitle: 'పుష్ నోటిఫికేషన్లను అనుకూలీకరించండి',
      whatsapp: 'మాకు వాట్సాప్‌లో సందేశం పంపండి',
      about: 'యాప్ గురించి',
      aboutSubtitle: 'Remyndnow యాప్ వివరాలు',
      help: 'సహాయం & మద్దతు',
      helpSubtitle: 'సహాయం కావాలా? సులభంగా చేరుకోండి',
      delete: 'మీ ఖాతాను తొలగించండి',
      deleteSubtitle: 'మీరు వెళ్లిపోతున్నందుకు మేము విచారిస్తున్నాం.',
      faq: 'తరచుగా అడిగే ప్రశ్నలు',
      faqSubtitle: 'మీకు తెలియాల్సిన ప్రతిదీ',
      logout: 'లాగ్ అవుట్',
      Privacy: 'గోప్యతా విధానం',
      Terms_cond: 'నిబంధనలు మరియు షరతులు',
      accountDeleteTitle: 'ఖాతాను తొలగించండి',
      accountDeleteSubtitle: 'మీరు వెళ్లిపోతున్నందుకు మేము విచారిస్తున్నాం.',
      accountDeleteDesc:
        'ఖాతాను తొలగించడం శాశ్వతం. మీ డేటా, బుకింగ్స్, సందేశాలు, ఫోటోలు అన్నీ తొలగించబడతాయి. ఈ చర్య తిరిగి తీసుకోలేము.',

      reasonPlaceholder: 'ఈ యాప్ ఉపయోగకరంగా అనిపించడం లేదు',
      reasonPrivacy: 'నాకు గోప్యతపై ఆందోళన ఉంది',
      reasonTooManyNotifications: 'నాకు చాలా నోటిఫికేషన్లు వస్తున్నాయి',
      reasonDuplicate: 'నేను డూప్లికేట్ ఖాతాను సృష్టించాను',
      reasonOther: 'ఇతర',
      reasonOtherPlaceholder: 'టైప్ చేయండి',

      deleteButton: 'ఖాతాను తొలగించండి',
      cancelButton: 'రద్దు చేయి',

      confirmTitle: 'మీకు ఖచ్చితంగా తెలుసా?',
      confirmDesc: 'ఈ చర్య శాశ్వతం. మీ మొత్తం డేటా తొలగించబడుతుంది.',
      confirmCancel: 'లేదు, నా ఖాతాను ఉంచండి',
      confirmDelete: 'అవును, తొలగించండి',
      suport_title: 'ఏవైనా ప్రశ్నలు లేదా అభిప్రాయాలున్నాయా?',
      suport_subtitle:
        'మీకు ఏమైనా ప్రశ్నలు, అభిప్రాయాలు లేదా మమ్మల్ని మెరుగుపరచడంలో సహాయపడే సూచనలు ఉన్నట్లయితే, దయచేసి మాకు తెలియజేయడంలో వీలేని సంకోచం తీసుకోకండి. మేము మీ ఆలోచనలను నిజమైన విలువగా భావిస్తాము, Remyndnow మీ కోసం ఎలా ఉత్తమంగా మారచ్చో తెలుసుకోవాలని ఆసక్తిగా ఉన్నాము. meille ఇమెయిల్ పంపండి — మేము ఎప్పుడూ వినడానికి సిద్ధంగా ఉన్నాము.',
    },
    DeleteAccount: {
      title: 'ఖాతాను తొలగించండి',
      subtitle: 'మీరు వెళ్లిపోతున్నందుకు మేము విచారిస్తున్నాం.',
      reason_label: 'విడిచిపెట్టే కారణం',
      placeholder: 'ఇక్కడ నమోదు చేయండి',
      delete_btn: 'ఖాతాను తొలగించండి',
      cancel_btn: 'రద్దు చేయి',
      confirm_title: 'మీకు ఖచ్చితంగా తెలుసా?',
      confirm_desc: 'ఈ చర్య శాశ్వతం. మీ మొత్తం డేటా తొలగించబడుతుంది.',
      keep_account: 'లేదు, నా ఖాతాను ఉంచండి',
      yes_delete: 'అవును, తొలగించండి',
    },
    Festivals: {
      title: 'పండుగలు',
      month: 'జులై 2023',
      know_more: 'ఇంకా తెలుసుకోండి',
      no_festivals: 'ఈ నెలలో పండుగలు లేవు.',
      upcoming_festivals: 'రాబోయే పండుగలు',
      view_details: 'వివరాలను చూడండి',
      search: 'శోధన',
    },
    Temple: {
      Temple: 'దేవాలయం',
      aboutTitle: 'మా OurTemples.info గురించి',
      aboutText1:
        'సమృద్ధిగా, విశ్వసనీయమైన వివరాలతో హిందూ దేవాలయాలను అన్వేషించండి. సందర్శించండి',
      aboutText2:
        ', భారతదేశవ్యాప్తంగా హిందూ దేవాలయాలను ప్రాంతం మరియు దేవుడి ఆధారంగా వర్గీకరించిన ఒకే ఒక పోర్టల్.',
      ourTemples: 'మా దేవాలయాలు',
      points:
        '• చరిత్ర & ప్రాముఖ్యత – ప్రతి పవిత్ర స్థలంలోని వారసత్వం మరియు కథలు\n\n• సమయాలు & పూజా వివరాలు – తెరవబడే సమయాలు, రోజువారీ పూజలు మరియు ప్రత్యేక పూజా షెడ్యూల్స్\n\n• ఎలా చేరుకోవాలి & సమీపంలోని విశేషాలు – దారినిర్దేశాలు, స్థానిక భూభాగం మరియు సమీపంలోని దేవాలయాలు లేదా ఇతర ప్రదేశాలు',
      closingText:
        'మీరు యాత్రను ప్లాన్ చేస్తున్నారా లేదా ఇంటి నుండి ఆధ్యాత్మిక వారసత్వాన్ని అన్వేషిస్తున్నారా,',
      closingText2:
        'మీ నమ్మకమైన మార్గదర్శి—స్వచ్ఛంద సేవకులు సేకరించి, మీలాంటి భక్తుల కోసం రూపొందించినది.',
    },
    HomeDetails: {
      reminderMe: 'నన్ను గుర్తు చేయి',
      reminderEnabled: 'రిమైండర్ ప్రారంభించబడింది',
      panchangTitle: 'పంచాంగం',
      panchangFor: 'కు పంచాంగం',
      aboutFestival: 'పండుగ గురించి',
      festivalHighlights: 'పండుగ ముఖ్యాంశాలు',
      regionalNames: 'ప్రాంతీయ పేర్లు',
      duration: 'వ్యవధి',
      dailySignificance: 'దైనందిన ప్రాధాన్యం',
      history: 'చరిత్ర',
      templesToVisit: 'సందర్శించాల్సిన దేవాలయాలు',
      otherInfo: 'ఇతర సమాచారం',
      statesCelebrated: 'జరుపుకునే రాష్ట్రాలు',
      upcomingFestivals: 'రాబోయే పండుగలు',
      setReminder: 'గుర్తు చేయు సెట్చేయి',
      reminderDesc: 'మేము ఈ రోజుల్లో ఉదయం 6 గంటలకు మీకు గుర్తు చేస్తాము',
      startPhrase: 'మేము మీకు',
      endPhrase: 'ఈ రోజుల్లో',
      beforeEkadashi: 'ముందు',
      onEkadashi: 'ప్రతిదానిపై',
      cancel: 'రద్దు చేయి',
      confirm: 'నిర్ధారించు',
      Vrat: 'పండుగ/వ్రతాన్ని ఎంచుకోండి',
      select_language: 'భాషను ఎంచుకోండి',
      description: 'మా వద్ద క్రింది భాషలు అందుబాటులో ఉన్నాయి',
      continue: 'కొనసాగించండి',
    },
  },
});
